#!/usr/bin/env python3
"""Fail if any commit message, or the pull request title or body, credits a second author.

Usage: check-attribution.py [REPO]      (REPO defaults to the current directory)

The repository has one author. GitHub lists every address named in a Co-authored-by
trailer as a contributor, so this check rejects:

  - any "Co-authored-by:" trailer,
  - any "Generated with" or "Generated by" line,
  - any noreply address other than GitHub's own users.noreply.github.com.

It scans every commit reachable from HEAD, so history that was cleaned stays clean, plus
the PR_TITLE and PR_BODY environment variables when continuous integration sets them.

Exit codes:
  0  scanned at least one commit and found nothing
  1  found at least one match
  2  could not run: not a git repository, a shallow clone, or no commits
"""

from __future__ import annotations

import os
import re
import subprocess
import sys

PATTERNS = [
    ("co-author trailer", re.compile(r"^\s*co-authored-by\s*:", re.IGNORECASE | re.MULTILINE)),
    ("generated-with line", re.compile(r"\bgenerated\s+(?:with|by)\b", re.IGNORECASE)),
    (
        "third-party noreply address",
        re.compile(r"\bnoreply@(?!users\.noreply\.github\.com\b)[\w.-]+", re.IGNORECASE),
    ),
]


def findings(label: str, text: str) -> list[str]:
    return [f"{label}: {name}" for name, pattern in PATTERNS if pattern.search(text)]


def git(repo: str, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", repo, *args], check=True, capture_output=True, text=True
    ).stdout


def main(argv: list[str]) -> int:
    repo = argv[0] if argv else "."
    try:
        if git(repo, "rev-parse", "--is-shallow-repository").strip() == "true":
            print("cannot check a shallow clone; fetch the full history", file=sys.stderr)
            return 2
        log = git(repo, "log", "--format=%h%x00%B%x1e", "HEAD")
    except (subprocess.CalledProcessError, FileNotFoundError) as error:
        print(f"cannot read git history: {error}", file=sys.stderr)
        return 2
    commits = [entry.strip("\n") for entry in log.split("\x1e") if entry.strip("\n")]
    if not commits:
        print("no commits to check", file=sys.stderr)
        return 2
    hits: list[str] = []
    for entry in commits:
        sha, _, message = entry.partition("\x00")
        hits += findings(f"commit {sha}", message)
    for name in ("PR_TITLE", "PR_BODY"):
        hits += findings(name.lower().replace("_", " "), os.environ.get(name, ""))
    for hit in hits:
        print(hit)
    print(f"checked {len(commits)} commits, {len(hits)} hits")
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
