#!/usr/bin/env python3
"""Fail if any commit credits or is made by anyone other than the repository owner.

Usage: check-attribution.py [REPO]      (REPO defaults to the current directory)

The repository has one author. GitHub lists every address named in a Co-authored-by
trailer as a contributor, so this check rejects:

  - any "Co-authored-by:" trailer,
  - any "Generated with" or "Generated by" line,
  - any noreply address other than GitHub's own users.noreply.github.com.

It also rejects any commit whose author is not listed in .github/allowed-authors, or whose
committer is neither listed there nor GitHub's own merge identity (noreply@github.com), so
a bot or automation account cannot become a contributor. Merge commits are skipped for the
author check: main requires linear history, and pull request checkouts are synthetic merges.

It scans every commit reachable from HEAD, so history that was cleaned stays clean, plus
the PR_TITLE and PR_BODY environment variables when continuous integration sets them.

Exit codes:
  0  scanned at least one commit and found nothing
  1  found at least one match
  2  could not run: not a git repository, a shallow clone, no commits, or no
     .github/allowed-authors file
"""

from __future__ import annotations

import os
from pathlib import Path
import re
import subprocess
import sys

PATTERNS = [
    ("co-author trailer", re.compile(r"^\s*co-authored-by\s*:", re.IGNORECASE | re.MULTILINE)),
    ("generated-with line", re.compile(r"\bgenerated\s+(?:with|by)\b", re.IGNORECASE)),
    (
        "third-party noreply address",
        re.compile(r"\bnoreply@(?!users\.noreply\.github\.com\b)[\w.-]+", re.IGNORECASE),
    ),
]


def findings(label: str, text: str) -> list[str]:
    return [f"{label}: {name}" for name, pattern in PATTERNS if pattern.search(text)]


def git(repo: str, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", repo, *args], check=True, capture_output=True, text=True
    ).stdout


GITHUB_MERGE_IDENTITY = "noreply@github.com"


def allowed_authors(repo: str) -> set[str] | None:
    path = Path(repo) / ".github" / "allowed-authors"
    if not path.is_file():
        return None
    lines = (line.strip().lower() for line in path.read_text(encoding="utf-8").splitlines())
    return {line for line in lines if line and not line.startswith("#")}


def main(argv: list[str]) -> int:
    repo = argv[0] if argv else "."
    allowed = allowed_authors(repo)
    if not allowed:
        print("missing or empty .github/allowed-authors", file=sys.stderr)
        return 2
    try:
        if git(repo, "rev-parse", "--is-shallow-repository").strip() == "true":
            print("cannot check a shallow clone; fetch the full history", file=sys.stderr)
            return 2
        log = git(repo, "log", "--format=%h%x00%P%x00%ae%x00%ce%x00%B%x1e", "HEAD")
    except (subprocess.CalledProcessError, FileNotFoundError) as error:
        print(f"cannot read git history: {error}", file=sys.stderr)
        return 2
    commits = [entry.strip("\n") for entry in log.split("\x1e") if entry.strip("\n")]
    if not commits:
        print("no commits to check", file=sys.stderr)
        return 2
    hits: list[str] = []
    for entry in commits:
        sha, parents, author, committer, message = entry.split("\x00", 4)
        hits += findings(f"commit {sha}", message)
        if len(parents.split()) < 2:
            if author.lower() not in allowed:
                hits.append(f"commit {sha}: author {author} is not in .github/allowed-authors")
            if committer.lower() not in allowed | {GITHUB_MERGE_IDENTITY}:
                hits.append(f"commit {sha}: committer {committer} is not allowed")
    for name in ("PR_TITLE", "PR_BODY"):
        hits += findings(name.lower().replace("_", " "), os.environ.get(name, ""))
    for hit in hits:
        print(hit)
    print(f"checked {len(commits)} commits, {len(hits)} hits")
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
